# Generated by Django 2.0 on 2018-01-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180111_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.CharField(choices=[('le', 'Leisure'), ('pe', 'Personal'), ('ed', 'Educational'), ('pr', 'Professional')], default='le', max_length=2),
            preserve_default=False,
        ),
    ]
