# Generated by Django 2.0 on 2018-01-14 16:06

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180113_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='position',
            field=geoposition.fields.GeopositionField(default={'lat': 51.44, 'lng': 5.48}, max_length=42),
            preserve_default=False,
        ),
    ]
