# Generated by Django 2.0 on 2018-01-14 18:55

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_event_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='position',
            field=geoposition.fields.GeopositionField(default='51.447,5.484', max_length=42),
        ),
    ]
