# Generated by Django 2.0 on 2018-01-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180115_0903'),
        ('app', '0009_event_position'),
    ]

    operations = [
    ]
