# Generated by Django 2.0 on 2018-01-15 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_merge_20180115_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='XattendsY',
            fields=[
                ('p_key', models.AutoField(primary_key=True, serialize=False)),
                ('x_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name='Date_format: YYYY-MM-DD HH:mm'),
        ),
        migrations.AddField(
            model_name='xattendsy',
            name='y_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event'),
        ),
    ]
