# Generated by Django 2.0 on 2018-01-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180115_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xattendsy',
            name='p_key',
        ),
        migrations.AddField(
            model_name='xattendsy',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
